#!/bin/bash

sudo xbps-install -S  > /dev/null 2>&1
UPDATES=$(xbps-install  -Mun | awk '{print $2}' | sort | uniq -c | xargs)
if [ -z "$UPDATES" ]; then
    echo "﨓" > /home/<user>/.cache/xbps-updates
else
   echo "$UPDATES" > /home/<user>/.cache/xbps-updates
fi
